# Label Validation Workflow Template
#
# This workflow validates that issues have required labels before state transitions.
# Copy to .github/workflows/validate-labels.yml and customize the label patterns.
#
# Validation Rules:
#   - state:implementation requires component:* label
#   - state:verification requires work-type:* label
#   - Issue close requires priority:* label
#
# Permissions: This workflow requires issues:read permission (default for GITHUB_TOKEN).
# No write permissions needed - it only reports warnings/errors in workflow output.
#
# Customization: Update the LABEL_* environment variables to match your repository's
# label naming conventions.

name: Validate Labels

on:
  issues:
    types: [labeled, unlabeled, closed]

env:
  # Label patterns (customize for your repository)
  LABEL_COMPONENT_PATTERN: "^component:"
  LABEL_WORKTYPE_PATTERN: "^work-type:"
  LABEL_PRIORITY_PATTERN: "^priority:"

  # State labels that trigger validation
  STATE_IMPLEMENTATION: "state:implementation"
  STATE_VERIFICATION: "state:verification"

  # Labels that skip validation (early lifecycle states)
  STATE_NEW_FEATURE: "state:new-feature"
  STATE_GROOMING: "state:grooming"
  STATE_REFINEMENT: "state:refinement"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Get Issue Labels
        id: labels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          LABELS=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            --jq '.labels[].name' 2>&1) || {
            echo "::warning title=API Error::Failed to fetch issue labels: $LABELS"
            echo "labels=" >> $GITHUB_OUTPUT
            exit 0
          }
          echo "Current labels:"
          echo "$LABELS"
          echo "labels<<EOF" >> $GITHUB_OUTPUT
          echo "$LABELS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine Validation Requirements
        id: requirements
        run: |
          LABELS="${{ steps.labels.outputs.labels }}"
          EVENT_ACTION="${{ github.event.action }}"
          IS_CLOSED="${{ github.event.issue.state == 'closed' }}"

          echo "Event action: $EVENT_ACTION"
          echo "Issue closed: $IS_CLOSED"

          # Determine which validations to run
          VALIDATE_COMPONENT=false
          VALIDATE_WORKTYPE=false
          VALIDATE_PRIORITY=false

          # Check if in implementation state
          if echo "$LABELS" | grep -qF "$STATE_IMPLEMENTATION"; then
            VALIDATE_COMPONENT=true
          fi

          # Check if in verification state
          if echo "$LABELS" | grep -qF "$STATE_VERIFICATION"; then
            VALIDATE_COMPONENT=true  # Must still have component
            VALIDATE_WORKTYPE=true
          fi

          # Check if issue is being closed
          if [ "$IS_CLOSED" = "true" ]; then
            VALIDATE_COMPONENT=true
            VALIDATE_WORKTYPE=true
            VALIDATE_PRIORITY=true
          fi

          # Check if in early lifecycle state (skip validation)
          if echo "$LABELS" | grep -qE "^($STATE_NEW_FEATURE|$STATE_GROOMING|$STATE_REFINEMENT)$"; then
            if [ "$IS_CLOSED" != "true" ]; then
              echo "Early lifecycle state detected, skipping validation"
              VALIDATE_COMPONENT=false
              VALIDATE_WORKTYPE=false
              VALIDATE_PRIORITY=false
            fi
          fi

          echo "validate_component=$VALIDATE_COMPONENT" >> $GITHUB_OUTPUT
          echo "validate_worktype=$VALIDATE_WORKTYPE" >> $GITHUB_OUTPUT
          echo "validate_priority=$VALIDATE_PRIORITY" >> $GITHUB_OUTPUT

      - name: Validate Labels
        id: validate
        run: |
          LABELS="${{ steps.labels.outputs.labels }}"
          VALIDATE_COMPONENT="${{ steps.requirements.outputs.validate_component }}"
          VALIDATE_WORKTYPE="${{ steps.requirements.outputs.validate_worktype }}"
          VALIDATE_PRIORITY="${{ steps.requirements.outputs.validate_priority }}"

          ERRORS=0
          WARNINGS=0

          # Validate component label
          if [ "$VALIDATE_COMPONENT" = "true" ]; then
            if echo "$LABELS" | grep -qE "$LABEL_COMPONENT_PATTERN"; then
              echo "Component label present"
            else
              echo "::warning title=Missing Component Label::Issue requires a 'component:*' label (e.g., component:api, component:skill). Add one before proceeding."
              WARNINGS=$((WARNINGS + 1))
            fi
          fi

          # Validate work-type label
          if [ "$VALIDATE_WORKTYPE" = "true" ]; then
            if echo "$LABELS" | grep -qE "$LABEL_WORKTYPE_PATTERN"; then
              echo "Work-type label present"
            else
              echo "::warning title=Missing Work-Type Label::Issue requires a 'work-type:*' label (e.g., work-type:new-feature, work-type:bug). Add one before proceeding."
              WARNINGS=$((WARNINGS + 1))
            fi
          fi

          # Validate priority label (required for close)
          if [ "$VALIDATE_PRIORITY" = "true" ]; then
            if echo "$LABELS" | grep -qE "$LABEL_PRIORITY_PATTERN"; then
              echo "Priority label present"
            else
              echo "::error title=Missing Priority Label::Issue requires a 'priority:*' label (e.g., priority:p0, priority:p2) before closing."
              ERRORS=$((ERRORS + 1))
            fi
          fi

          # Summary
          if [ $ERRORS -gt 0 ] || [ $WARNINGS -gt 0 ]; then
            echo "Validation completed: $ERRORS errors, $WARNINGS warnings"
            echo "valid=false" >> $GITHUB_OUTPUT
          else
            echo "All required labels present"
            echo "valid=true" >> $GITHUB_OUTPUT
          fi

          # Don't fail the workflow - just report
          exit 0
